apiVersion: v1
kind: BuildConfig
metadata:
  name: service-registry-center-artifact-build
spec:
  output:
    to:
      kind: DockerImage
      name: registry.felix.com/service-registry-center/artifact-image:latest
    pushSecret:
      name: docker-registry
  source:
    type: Git
    git:
      uri: https://github.com/SZFelixHuang/service-registry-center.git
  secrets:
    - secret:
        name: github
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: s2i-builder-image:latest
      pullSecret:
        name: docker-registry
    type: Source
---
apiVersion: v1
kind: BuildConfig
metadata:
  name: service-registry-center-runtime-build
spec:
  output:
    to:
      kind: DockerImage
      name: registry.felix.com/service-registry-center/runtime-image:latest
    pushSecret:
      name: docker-registry
  source:
    type: Dockerfile
    dockerfile: |- 
      FROM runtime-image:latest 
      COPY service-registry-center-1.0.jar /service-registry-center-1.0.jar 
      ENTRYPOINT ['java','-jar','/service-registry-center-1.0.jar']
    images:
    - from:
        kind: ImageStreamTag
        name: service-registry-center-artifact-image:latest
      pullSecret:
        name: docker-registry
      paths:
      - sourcePath: /tmp/src/target/service-registry-center-1.0.jar
        destinationDir: "."
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: runtime-image:latest
      pullSecret:
        name: docker-registry
    type: Docker
  triggers:
  - imageChange: {}
    type: ImageChange