apiVersion: v1
kind: BuildConfig
metadata:
  name: service-registry-center-artifact-build
spec:
  output:
    to:
      kind: DockerImage
      name: registry.felix.com/service-registry-center/artifact-image:latest
    pushSecret:
      name: docker-registry
  source:
    type: Git
    sourceSecret:
      name: gitlab
    git:
      uri: http://gitlab.felix.com/root/service-registry-center.git
      ref: master
  strategy:
    sourceStrategy:
      from:
        kind: DockerImage
        name: registry.felix.com/devops/s2i-builder-image:latest
      pullSecret:
        name: docker-registry
    type: Source
---
apiVersion: v1
kind: BuildConfig
metadata:
  name: service-registry-center-runtime-build
spec:
  output:
    to:
      kind: DockerImage
      name: registry.felix.com/service-registry-center/runtime-image:latest
    pushSecret:
      name: docker-registry
  source:
    type: Dockerfile
    dockerfile: |- 
      FROM registry.felix.com/service-registry-center/runtime-image:latest 
      COPY service-registry-center-1.0.jar /service-registry-center-1.0.jar 
      ENTRYPOINT ["java","-jar", "-Dspring.profiles.active=${profile}", "/service-registry-center-1.0.jar"]
    images:
    - from:
        kind: DockerImage
        name: registry.felix.com/service-registry-center/artifact-image:latest
      forcePull: true 
      pullSecret:
        name: docker-registry
      paths:
      - sourcePath: /tmp/src/target/service-registry-center-1.0.jar
        destinationDir: "."
  strategy:
    dockerStrategy:
      from:
        kind: DockerImage
        name: registry.felix.com/devops/runtime-image:latest
      pullSecret:
        name: docker-registry
    type: Docker
  triggers:
  - imageChange: {}
    type: ImageChange