apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/display-name: s2i-builder-image
  generation: 1
  name: s2i-builder-image
spec:
  lookupPolicy:
    local: false
  dockerImageRepository: 'registry.felix.com/devops/s2i-builder-image'
  tags:
    - annotations:
        openshift.io/display-name: openshift s2i-builder-image
        openshift.io/provider-display-name: 'Felix'
        tags: 's2i-builder-image'
        version: latest
      from:
        kind: DockerImage
        name: 's2i-builder-image:latest'
      pullSecret:
        name: docker-registry
      generation: 1
      name: 'latest'
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/display-name: runtime-image
  generation: 2
  name: runtime-image
spec:
  lookupPolicy:
    local: false
  dockerImageRepository: 'registry.felix.com/devops/runtime-image'
  tags:
    - annotations:
        openshift.io/display-name: openshift runtime-image
        openshift.io/provider-display-name: 'Felix'
        tags: 'runtime-image'
        version: latest
      from:
        kind: DockerImage
        name: 'runtime-image:latest'
      pullSecret:
        name: docker-registry
      generation: 2
      name: 'latest'
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/display-name: service-registry-center-artifact-image
  generation: 3
  name: service-registry-center-artifact-image
spec:
  lookupPolicy:
    local: false
  dockerImageRepository: 'registry.felix.com/service-registry-center/artifact-image'
  tags:
    - annotations:
        openshift.io/display-name: openshift service-registry-center-artifact-image
        openshift.io/provider-display-name: 'Felix'
        tags: 'service-registry-center-artifact-image'
        version: latest
      from:
        kind: DockerImage
        name: 'artifact-image:latest'
      pullSecret:
        name: docker-registry
      generation: 3
      name: 'latest'
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/display-name: service-registry-center-runtime-image
  generation: 4
  name: service-registry-center-runtime-image
spec:
  lookupPolicy:
    local: false
  dockerImageRepository: 'registry.felix.com/service-registry-center/runtime-image'
  tags:
    - annotations:
        openshift.io/display-name: openshift service-registry-center-runtime-image
        openshift.io/provider-display-name: 'Felix'
        tags: 'service-registry-center-runtime-image'
        version: latest
      from:
        kind: DockerImage
        name: 'runtime-image:latest'
      pullSecret:
        name: docker-registry
      generation: 4
      name: 'latest'