apiVersion: v1
kind: BuildConfig
metadata:
  name: service-registry-center-build-pipeline
spec:
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        pipeline {
            agent any
            stages {
                stage('build-artifact-image') {                 
                    steps {
                        script {
                            openshift.withCluster() {
                                openshift.withProject("spring-cloud") {
                                    def buildSelector = openshift.selector("bc", "service-registry-center-artifact-build");
                                    buildSelector.logs('-f');
                                    buildSelector.startBuild();
                                    def builds = buildSelector.related('builds');
                                    builds.watch {
                                     def isRunning = false;
                                     it.withEach {
                                        if(it.object().status.phase == "Running"){
                                            echo "bc [service-registry-center-artifact-build] has created build: ${it.object().metadata.name}";
                                            isRunning = true;
                                        }
                                     }
                                     return isRunning;
                                    }
                                    builds.watch {
                                        if ( it.count() == 0 ) return false;
                                        def allDone = true
                                        it.withEach {
                                            def buildModel = it.object() 
                                            if ( it.object().status.phase != "Complete" ) {
                                                echo "${it.object().metadata.name} is in '${it.object().status.phase}' status.";
                                                allDone = false
                                            }
                                        }
                                        if(allDone){
                                            echo "artifact building was completed.";
                                        }
                                        return allDone;
                                    }
                                }
                            }
                        }
                    }
                }
                stage('build-runtime-image') {
                    steps {
                        script {
                            openshift.withCluster() {
                                openshift.withProject("spring-cloud") {
                                    def buildSelector = openshift.selector("bc", "service-registry-center-runtime-build");
                                    buildSelector.logs('-f');
                                    buildSelector.startBuild();
                                    def builds = buildSelector.related('builds');
                                    builds.watch {
                                       def isDone = false;
                                       it.withEach {
                                        if(it.object().status.phase == "Running"){
                                            echo "bc [service-registry-center-runtime-build] has created build: ${it.object().metadata.name}";
                                            isDone = true;
                                        }
                                     }
                                     return isDone;
                                    }
                                    builds.watch {
                                        if ( it.count() == 0 ) return false;
                                        def allDone = true;
                                        it.withEach {
                                            def buildModel = it.object() 
                                            if ( it.object().status.phase != "Complete" ) {
                                                echo "${it.object().metadata.name} is in '${it.object().status.phase}' status.";
                                                allDone = false
                                            }
                                        }
                                        if(allDone){
                                            echo "artifact building was completed.";
                                        }
                                        return allDone;
                                    }
                                }
                            }
                        }
                    }
                }
            }
         }
    type: JenkinsPipeline